### PR TITLE
chore: update deps

### PR DESCRIPTION
**Pull request by brycemcwilliams**

### CODE REVIEW

**Comment by selfup** [comment]
First of all thanks :pray:

If we move compiled assets to `dist` we can no longer deploy to github pages :thinking:

Unless we change the public path to `dist` and refer to that path in the `index.html`

Let me know what you think

**Comment by brycemcwilliams** [comment]
No problem bro,

I normally use something like the following:


```
git worktree add dist gh-pages
npm bulid
cd dist
git add --all
git commit -m "chore: update gh-pages"
git push origin gh-pages
```
What are your thoughts? You could add a script,

**Comment by selfup** [comment]
Yea adding as a script could work!

Let me try this out when I get home today.

I wouldn't mind making a script directory 👍

**Comment by selfup** [comment]
Could you also update Hyperapp to 1.2.5? Thanks 🙏

**Comment by selfup** [comment]
And If you can just update the instructions in the README on how to deploy to GH pages that would be great 👍

**Comment by selfup** [comment]
Once you update the README and upgrade to HA 1.2.5, I am down to merge :)

**Comment by brycemcwilliams** [comment]
Sweet have done as requested, let me know what you think 👍

**Comment by selfup** [comment]
Sweet! Looks good. Tests pass 🎉

**Pull request merged**
