### PR TITLE
Tweaks template markup and styles

### PR DESCRIPTION
**Pull request by lukejacksonn**
I know style is somewhat superfluous in project like this but things should look as good as they work 💯 I tweaked the styles of the document and counter, see what you think:

## Before

screen shot 2017-02-18 at 1 11 24 am

## After

screen shot 2017-02-18 at 1 11 18 am

### CODE REVIEW

**Comment by jbucaran** [comment]
Als, perhaps "With JSX" is not really needed?

**Comment by lukejacksonn** [comment]
I was going on the assumption that there would be "With HyperX and Browserify" and other such combinations. Perhaps it's better to be explicit if so.

**Comment by jbucaran** [comment]
Fair enough! :)

**Comment by selfup** [comment]
This is great! Thanks a bunch 😄

**Comment by selfup** [comment]
Let me know we you are done! I am going to bed soon so I might wait until tomorrow haha

**Comment by lukejacksonn** [comment]
I'm about done man so :shipit: from me! About to sleep too 😴

**Comment by selfup** [comment]
If you could remove the `yarn.lock` that would be great!

I'll review it tomorrow when my brain is in better shape haha

**Comment by selfup** [comment]
Ok hold on tight!

**Comment by tunnckoCore** [comment]
Cool, looks better.

**Pull request merged**
