### PR TITLE
Add TOC and other tweak/align improvements.

### PR DESCRIPTION
**Pull request by JorgeBucaran**
Adds a table of contents, links and other small improvements. I also created a gif to show the live example, but didn't include it on this PR.

<div align=center>
  <a href=http://selfup.github.io/hyperapp-one>
    
  </a>
</div>

### CODE REVIEW

**Comment by selfup** [comment]
@JorgeBucaran you can go ahead and add it to the PR now that you have the link 👍

**Comment by JorgeBucaran** [comment]
@selfup Done.

**Comment by JorgeBucaran** [comment]
Also please update the repo's description:

> Hyperapp One is a Webpack boilerplate for quickstarting a web application with Hyperapp, JSX, and Airbnb's JavaScript Styleguide via ESLint. https://selfup.github.io/hyperapp-one

screen shot 2018-01-23 at 9 01 31

**Comment by selfup** [comment]
Ok done!

**Comment by selfup** [comment]
Ok awesome! Thanks 🙏 Going to merge 🎉

**Pull request merged**
