### PR TITLE
update packages - introduce scope hoisting

### PR DESCRIPTION
**Pull request by selfup**
For reference: https://medium.com/webpack/webpack-3-official-release-15fd2dd8f07b

### CODE REVIEW

**Comment by selfup** [comment]
### Wicked Fast!

I know the example app is small, but without any extensions (incognito) this is wicked fast!

screen shot 2017-09-08 at 12 20 26 pm

**Comment by selfup** [comment]
Incognito https://selfup.github.io/hyperapp-one

screen shot 2017-09-08 at 12 24 31 pm

@jbucaran 🎉

**Comment by selfup** [comment]
And even crazier:

screen shot 2017-09-08 at 12 29 14 pm

**Comment by jbucaran** [comment]
That's nuts!

**Comment by selfup** [comment]
I know haha!

**Pull request merged**
