### PR TITLE
have babel transpile and use babili to minify

### PR DESCRIPTION
**Pull request by selfup**
@jbucaran This will minify the code as well as transpile it 😄 when doing `npm run build`

🎉

### CODE REVIEW

**Comment by selfup** [comment]
### Before

screen shot 2017-02-09 at 1 47 02 am


### After

screen shot 2017-02-09 at 1 50 00 am

**Comment by jbucaran** [comment]
Yeah, it should be less after stripping hyperx. 

For JSX support you'll want to include the pragma in the .babelrc

```
{
  "plugins": [
    ["transform-react-jsx", { "pragma":"h" }]
  ]
}
```

**Comment by selfup** [comment]
Ok then i might keep this repo focused on the template strings then. Might need your help with stripping hyperx to do the transform 😄

**Comment by jbucaran** [comment]
@selfup Either is fine. If you are going to include a .babelrc, might as well add the pragma also, what do you think?

**Comment by selfup** [comment]
Sure I will take a look tomorrow. Thanks for the pointers so far!

**Comment by selfup** [comment]
Ok couldn't sleep haha

Ok I added JSX support (I tried, it works on 0.0.12 - kept it at 0.0.9 for now)

Keeping the template literals. Now they are being transpiled as well 🎉 (not transformed)

now we have 2 build commands:

`npm run build`

and

`npm run minify`

This also ensures that in dev mode we don't have minified code 😄

**Comment by jbucaran** [comment]
The current, soon to be gone, "hyperapp/hx" is only for Hyperx, so you should be able to use "hyperapp" already if you are using JSX.

Will release 0.0.13 in a few hours.

**Comment by selfup** [comment]
Yes I am aware but I wanted to keep the template strings as the base repo, so will upgrade tomorrow if you are indeed pushing up in a few hours 😄 

Thanks again for all the feedback

I'll go ahead and merge this tomorrow once I have had some sleep!

**Comment by jbucaran** [comment]
> Let me know if you don't mind me using JSX as the base example for this repo 😄

Of course not! Users should use whatever they find more convenient and my preferences should not get in the way! Go jsx! haha

**Pull request merged**
