### PR TITLE
Add favicon.

### PR DESCRIPTION
**Pull request by jbucaran**
👋

### CODE REVIEW

**Comment by jbucaran** [comment]
+0? I think I screwed up, or GitHub drag and drop thing didn't work. Can you see the favicon?

**Comment by selfup** [comment]
It just says binary file not shown...I think it might be right?

**Comment by selfup** [comment]
Seems good to me! 

https://raw.githubusercontent.com/jbucaran/hyperapp-one/77d3d82b4653ea6613c6310fbf58ff015fda9820/favicon.ico

:tada:

**Comment by selfup** [comment]
Ok weird it works locally but not online :thinking:

**Pull request merged**
